spring:
  application:
    name: gateway-service
  cloud:
    zookeeper:
      connect-string: localhost:2181
    discovery:
      enabled: true
    gateway:
      server:
        webmvc:
          routes:
            - id: catalog-service
              uri: lb://catalog-service
              predicates:
                - Path=/catalog/**
              filters:
                - StripPrefix=1
            - id: inventory-service
              uri: lb://inventory-service
              predicates:
                - Path=/inventory/**
              filters:
                - StripPrefix=1
            - id: price-service
              uri: lb://price-service
              predicates:
                - Path=/price/**
              filters:
                - StripPrefix=1
            - id: users-service
              uri: lb://users-service
              predicates:
                - Path=/users/**
              filters:
                - StripPrefix=1
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:9000/realms/ElZapato
springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    urls:
      - name: catalog
        url: /catalog/api-docs
      - name: inventory
        url: /inventory/api-docs
      - name: price
        url: /price/api-docs
      - name: users
        url: /users/api-docs
management:
  endpoints:
    web:
      exposure:
        include: "*"
server:
  port: 8080