spring:
  application:
    name: config-service
  cloud:
    config:
      server:
        git:
          uri: https://github.com/Frank18ci/configuration-zapateria-el-zapato-servicios-web
    zookeeper:
      connect-string: localhost:2181
    discovery:
      enabled: true

server:
  port: 8100